const Data = [
  {
    id: 1,
    category: "education",
    icon: "icon-graduation",
    year: "2021 - present",
    title: "Ho Chi Minh City University of Education",
    desc: "K47 student majoring in information technology - majoring in software technology",
  },
  {
    id: 2,
    category: "education",
    icon: "icon-graduation",
    year: "2018 - 2020",
    title: "An Nghia high school",
    desc: "",
  },
  {
    id: 3,
    category: "education",
    icon: "icon-graduation",
    year: "20014 - 2017",
    title: "An Thoi Dong Secondary School",
    desc: "",
  },
  {
    id: 4,
    category: "education",
    icon: "icon-graduation",
    year: "2009 - 2013",
    title: "An Thoi Primary School",
    desc: "",
  },
  {
    id: 5,
    category: "experience",
    icon: "icon-briefcase",
    year: "2019 - present",
    title: "Web Designer",
    desc: "",
  },
  {
    id: 6,
    category: "experience",
    icon: "icon-briefcase",
    year: "2013 - 2017",
    title: "Front-End Developer",
    desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
  },
  {
    id: 7,
    category: "experience",
    icon: "icon-briefcase",
    year: "2009 - 2013",
    title: "Back-End Developer",
    desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
  },
];

export default Data;
